
  CREATE TABLE "PIS_STORITVE_POS"."CALLBACK_POSILJANJE" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"VERSION" NUMBER(19,0) DEFAULT 0 NOT NULL ENABLE, 
	"ZAHTEVA_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(40 CHAR), 
	"CALLBACK_DATA" CLOB, 
	"CALLBACK_FILES" CLOB, 
	"CALLBACK_RESPONSE" CLOB, 
	"CALLBACK_SENT" NUMBER(1,0), 
	"CALLBACK_NEXT_ATTEMPT" TIMESTAMP (6), 
	"DATUM_CRE" TIMESTAMP (6) NOT NULL ENABLE, 
	"DATUM_MOD" TIMESTAMP (6), 
	"ODGOVOR_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_TBS" 
 LOB ("CALLBACK_DATA") STORE AS SECUREFILE (
  TABLESPACE "DATA_TBS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("CALLBACK_FILES") STORE AS SECUREFILE (
  TABLESPACE "DATA_TBS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("CALLBACK_RESPONSE") STORE AS SECUREFILE (
  TABLESPACE "DATA_TBS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  CREATE UNIQUE INDEX "PIS_STORITVE_POS"."PK_CALLBACK_POSILJANJE" ON "PIS_STORITVE_POS"."CALLBACK_POSILJANJE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_TBS" ;
ALTER TABLE "PIS_STORITVE_POS"."CALLBACK_POSILJANJE" ADD CONSTRAINT "PK_CALLBACK_POSILJANJE" PRIMARY KEY ("ID")
  USING INDEX "PIS_STORITVE_POS"."PK_CALLBACK_POSILJANJE"  ENABLE;
ALTER TABLE "PIS_STORITVE_POS"."CALLBACK_POSILJANJE" ADD CONSTRAINT "FK_CALLBACK_POS_ZAHTEVA" FOREIGN KEY ("ZAHTEVA_ID")
	  REFERENCES "PIS_STORITVE_POS"."ZAHTEVA" ("ID") ON DELETE CASCADE ENABLE;
ALTER TABLE "PIS_STORITVE_POS"."CALLBACK_POSILJANJE" ADD CONSTRAINT "FK_CALLBACK_POS_ODGOVOR" FOREIGN KEY ("ODGOVOR_ID")
	  REFERENCES "PIS_STORITVE_POS"."ODGOVOR" ("ID") ON DELETE CASCADE ENABLE;