
  CREATE TABLE "PIS_STORITVE_POS"."NAPAKA_ODGOVORA" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"VERSION" NUMBER(19,0) DEFAULT 0 NOT NULL ENABLE, 
	"ODGOVOR_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"SOURCE" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"ERROR_CODE" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"OPIS" VARCHAR2(2000 CHAR) NOT NULL ENABLE, 
	"DATUM_NAPAKE" TIMESTAMP (6) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"DATUM_CRE" TIMESTAMP (6) NOT NULL ENABLE, 
	"DATUM_MOD" TIMESTAMP (6), 
	"IDENT" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_TBS" ;
ALTER TABLE "PIS_STORITVE_POS"."NAPAKA_ODGOVORA" ADD CONSTRAINT "PK_NAPAKA" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE;