
  CREATE TABLE "PIS_STORITVE_POS"."ODGOVOR" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ZAHTEVA_ID" NUMBER(19,0), 
	"TIP_ZAHTEVE" VARCHAR2(100 CHAR), 
	"NASLOVNIK" VARCHAR2(100 CHAR), 
	"PUBLIC_ID" VARCHAR2(36 CHAR), 
	"ORGANIZACIJA_ID" VARCHAR2(100 CHAR), 
	"SIGNIRNA_OZNAKA" VARCHAR2(255 CHAR), 
	"DATA" CLOB, 
	"MESSAGE_ID" NUMBER(19,0), 
	"STATUS" VARCHAR2(40 CHAR) NOT NULL ENABLE, 
	"VIR" VARCHAR2(100 CHAR), 
	"DATUM_CRE" TIMESTAMP (6) NOT NULL ENABLE, 
	"DATUM_MOD" TIMESTAMP (6), 
	"FILES" CLOB, 
	"VERSION" NUMBER(19,0) DEFAULT 0 NOT NULL ENABLE, 
	"STATUS_INFO" VARCHAR2(4000 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PISAPI_TBS" 
 LOB ("DATA") STORE AS SECUREFILE (
  TABLESPACE "DATA_TBS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("FILES") STORE AS SECUREFILE (
  TABLESPACE "PISAPI_TBS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  CREATE UNIQUE INDEX "PIS_STORITVE_POS"."PK_ODGOVOR" ON "PIS_STORITVE_POS"."ODGOVOR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PISAPI_TBS" ;
  CREATE UNIQUE INDEX "PIS_STORITVE_POS"."UK_ODGOVOR_MESSAGE_VIR" ON "PIS_STORITVE_POS"."ODGOVOR" ("MESSAGE_ID", "VIR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PISAPI_TBS" ;
ALTER TABLE "PIS_STORITVE_POS"."ODGOVOR" ADD CONSTRAINT "PK_ODGOVOR" PRIMARY KEY ("ID")
  USING INDEX "PIS_STORITVE_POS"."PK_ODGOVOR"  ENABLE;
ALTER TABLE "PIS_STORITVE_POS"."ODGOVOR" ADD CONSTRAINT "UK_ODGOVOR_MESSAGE_VIR" UNIQUE ("MESSAGE_ID", "VIR")
  USING INDEX "PIS_STORITVE_POS"."UK_ODGOVOR_MESSAGE_VIR"  ENABLE;
ALTER TABLE "PIS_STORITVE_POS"."ODGOVOR" ADD CONSTRAINT "FK_ODGOVOR_ZAHTEVA" FOREIGN KEY ("ZAHTEVA_ID")
	  REFERENCES "PIS_STORITVE_POS"."ZAHTEVA" ("ID") ENABLE;