
  CREATE TABLE "PIS_STORITVE_POS"."PRAVICA" 
   (	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"APLIKACIJA" VARCHAR2(10 BYTE), 
	"MATICNA_STEVILKA" VARCHAR2(20 BYTE), 
	"CEH_REF" VARCHAR2(128 BYTE), 
	"DATUM_CRE" TIMESTAMP (6) NOT NULL ENABLE, 
	"DATUM_MOD" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_TBS" ;
  CREATE UNIQUE INDEX "PIS_STORITVE_POS"."PK_PRAVICA" ON "PIS_STORITVE_POS"."PRAVICA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_TBS" ;
ALTER TABLE "PIS_STORITVE_POS"."PRAVICA" ADD CONSTRAINT "PK_PRAVICA" PRIMARY KEY ("ID")
  USING INDEX "PIS_STORITVE_POS"."PK_PRAVICA"  ENABLE;