
  CREATE TABLE "PIS_STORITVE_POS"."PREVZEM" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"VERSION" NUMBER(19,0) NOT NULL ENABLE, 
	"ZAHTEVA_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"PREVZEM_OBDELAN" NUMBER(1,0) NOT NULL ENABLE, 
	"DATUM_OBVESTILA" TIMESTAMP (6) NOT NULL ENABLE, 
	"DATUM_CRE" TIMESTAMP (6) NOT NULL ENABLE, 
	"DATUM_MOD" TIMESTAMP (6), 
	"ODGOVOR_ID" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_TBS" ;
  CREATE UNIQUE INDEX "PIS_STORITVE_POS"."PK_PREVZEM" ON "PIS_STORITVE_POS"."PREVZEM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_TBS" ;
ALTER TABLE "PIS_STORITVE_POS"."PREVZEM" ADD CONSTRAINT "PK_PREVZEM" PRIMARY KEY ("ID")
  USING INDEX "PIS_STORITVE_POS"."PK_PREVZEM"  ENABLE;
ALTER TABLE "PIS_STORITVE_POS"."PREVZEM" ADD CONSTRAINT "FK_PREVZEM_ZAHTEVA" FOREIGN KEY ("ZAHTEVA_ID")
	  REFERENCES "PIS_STORITVE_POS"."ZAHTEVA" ("ID") ON DELETE CASCADE ENABLE;
ALTER TABLE "PIS_STORITVE_POS"."PREVZEM" ADD CONSTRAINT "FK_PREVZEM_ODGOVOR" FOREIGN KEY ("ODGOVOR_ID")
	  REFERENCES "PIS_STORITVE_POS"."ODGOVOR" ("ID") ON DELETE CASCADE ENABLE;