
  CREATE TABLE "PIS_STORITVE_POS"."PRIPONKA" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ZAHTEVA_ID" NUMBER(19,0), 
	"ELEMENT_ID" NUMBER(19,0), 
	"ELEMENT_SIFRA" VARCHAR2(255 CHAR), 
	"CEH_REF" VARCHAR2(255 CHAR), 
	"FILENAME" VARCHAR2(255 CHAR), 
	"IS_VLOGA" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PISAPI_TBS" ;
ALTER TABLE "PIS_STORITVE_POS"."PRIPONKA" ADD CONSTRAINT "PK_PRIPONKA" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PISAPI_TBS"  ENABLE;
ALTER TABLE "PIS_STORITVE_POS"."PRIPONKA" ADD CONSTRAINT "FK_PRIPONKA_ZAHTEVA" FOREIGN KEY ("ZAHTEVA_ID")
	  REFERENCES "PIS_STORITVE_POS"."ZAHTEVA" ("ID") ON DELETE CASCADE ENABLE;