
  CREATE TABLE "PIS_STORITVE_POS"."TASK" 
   (	"TASK_ID" NUMBER(18,0) DEFAULT "PIS_STORITVE_POS"."TASK_SEQ"."NEXTVAL", 
	"STATUS" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"REPEAT_COUNT" NUMBER(18,0) NOT NULL ENABLE, 
	"CONTEXT" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"CONTEXT_ID" VARCHAR2(100 CHAR), 
	"NEXT_RUN_TIME" TIMESTAMP (6), 
	"LOCK_TIME" TIMESTAMP (6), 
	"DATA" CLOB NOT NULL ENABLE, 
	"QUEUE" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"UNIQUE_FLAG" NUMBER(1,0) NOT NULL ENABLE, 
	"FORCE_PROCESSING" NUMBER(1,0) NOT NULL ENABLE, 
	"ERROR" CLOB, 
	"CREATED" TIMESTAMP (6) NOT NULL ENABLE, 
	"UPDATED" TIMESTAMP (6) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_TBS" 
 LOB ("DATA") STORE AS SECUREFILE (
  TABLESPACE "DATA_TBS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("ERROR") STORE AS SECUREFILE (
  TABLESPACE "DATA_TBS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
ALTER TABLE "PIS_STORITVE_POS"."TASK" ADD CONSTRAINT "PK_TASK" PRIMARY KEY ("TASK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE;