
  CREATE TABLE "PIS_STORITVE_POS"."TMP_TEST6" 
   (	"ID" NUMBER, 
	"IME" VARCHAR2(200 CHAR), 
	"PRIIMEK" VARCHAR2(200 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "PISAPI_TBS" ;