
  CREATE TABLE "PIS_STORITVE_POS"."ZAHTEVA" 
   (	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"TIP_ZAHTEVE" VARCHAR2(100 CHAR), 
	"NASLOVNIK" VARCHAR2(100 CHAR), 
	"PUBLIC_ID" VARCHAR2(36 CHAR) NOT NULL ENABLE, 
	"MNENJE_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"APLIKACIJA" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"ORGANIZACIJA_ID" VARCHAR2(100 CHAR), 
	"INSTITUCIJA" VARCHAR2(255 CHAR), 
	"MATICNA_STEVILKA" VARCHAR2(20 CHAR), 
	"DATA" CLOB, 
	"STRUKTURA_GRADIVA_ID" NUMBER(19,0), 
	"ZIP_ID" VARCHAR2(128 CHAR), 
	"STATUS" VARCHAR2(40 CHAR) NOT NULL ENABLE, 
	"DATUM_CRE" TIMESTAMP (6) NOT NULL ENABLE, 
	"DATUM_MOD" TIMESTAMP (6), 
	"CALLBACK_URL" VARCHAR2(255 CHAR), 
	"VERSION" NUMBER(19,0) DEFAULT 0 NOT NULL ENABLE, 
	"STATUS_INFO" VARCHAR2(4000 CHAR), 
	"TIP_STORITVE" VARCHAR2(255 CHAR), 
	"PRISTOJNOST" VARCHAR2(255 CHAR), 
	"VRSTA_MNENJA" VARCHAR2(255 CHAR), 
	"MATICNA_STEVILKA_RECIPIENTA" VARCHAR2(20 CHAR), 
	"ORGANIZACIJA_KODA" VARCHAR2(255 CHAR) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PISAPI_TBS" 
 LOB ("DATA") STORE AS SECUREFILE (
  TABLESPACE "DATA_TBS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
ALTER TABLE "PIS_STORITVE_POS"."ZAHTEVA" ADD CONSTRAINT "PK_ZAHTEVA" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PISAPI_TBS"  ENABLE;
ALTER TABLE "PIS_STORITVE_POS"."ZAHTEVA" ADD UNIQUE ("PUBLIC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA_TBS"  ENABLE;