CREATE USER PIS_STORITVE_POS IDENTIFIED BY PIS_STORITVE_POS DEFAULT TABLESPACE PISAPI_TBS TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
CREATE USER PIS_STORITVE_APP IDENTIFIED BY PIS_STORITVE_APP DEFAULT TABLESPACE PISAPI_TBS TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;

ALTER  USER PIS_STORITVE_POS       QUOTA UNLIMITED ON PISAPI_TBS;
ALTER  USER PIS_STORITVE_APP       QUOTA 0         ON PISAPI_TBS;

GRANT CREATE SESSION TO PIS_STORITVE_POS;
GRANT CREATE SESSION TO PIS_STORITVE_APP;
GRANT CREATE PROCEDURE TO PIS_STORITVE_POS;
GRANT CREATE SEQUENCE TO PIS_STORITVE_POS;
GRANT CREATE SYNONYM TO PIS_STORITVE_POS;
GRANT CREATE TABLE TO PIS_STORITVE_POS;
GRANT CREATE TRIGGER TO PIS_STORITVE_POS;
GRANT CREATE TYPE TO PIS_STORITVE_POS;
GRANT CREATE VIEW TO PIS_STORITVE_POS;
GRANT CREATE SYNONYM TO PIS_STORITVE_APP;
