CREATE TABLE "PIS_STORITVE_POS"."DATABASECHANGELOGLOCK"
   (    "ID" NUMBER(*,0) NOT NULL ENABLE,
        "LOCKED" NUMBER(1,0) NOT NULL ENABLE,
        "LOCKGRANTED" TIMESTAMP (6),
        "LOCKEDBY" VARCHAR2(255 CHAR),
         CONSTRAINT "PK_DATABASECHANGELOGLOCK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;

CREATE TABLE "PIS_STORITVE_POS"."DATABASECHANGELOG"
   (    "ID" VARCHAR2(255 CHAR) NOT NULL ENABLE,
        "AUTHOR" VARCHAR2(255 CHAR) NOT NULL ENABLE,
        "FILENAME" VARCHAR2(255 CHAR) NOT NULL ENABLE,
        "DATEEXECUTED" TIMESTAMP (6) NOT NULL ENABLE,
        "ORDEREXECUTED" NUMBER(*,0) NOT NULL ENABLE,
        "EXECTYPE" VARCHAR2(10 CHAR) NOT NULL ENABLE,
        "MD5SUM" VARCHAR2(35 CHAR),
        "DESCRIPTION" VARCHAR2(255 CHAR),
        "COMMENTS" VARCHAR2(255 CHAR),
        "TAG" VARCHAR2(255 CHAR),
        "LIQUIBASE" VARCHAR2(20 CHAR),
        "CONTEXTS" VARCHAR2(255 CHAR),
        "LABELS" VARCHAR2(255 CHAR),
        "DEPLOYMENT_ID" VARCHAR2(10 CHAR)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;

-- locked = 0
Insert into PIS_STORITVE_POS.DATABASECHANGELOGLOCK (ID,LOCKED,LOCKGRANTED,LOCKEDBY) values ('1','0',to_timestamp('24.06.26 09:17:41,785884000','DD.MM.RR HH24:MI:SSXFF'),'W012823 (192.168.2.132)');
commit;
