-- Create Database Lock Table
CREATE TABLE PIS_STORITVE_POS.LB_CHANGESLOCK (ID INTEGER NOT NULL, LOCKED NUMBER(1) NOT NULL, LOCKGRANTED TIMESTAMP, LOCKEDBY VARCHAR2(255), CONSTRAINT PK_LB_CHANGESLOCK PRIMARY KEY (ID));

-- Initialize Database Lock Table
DELETE FROM PIS_STORITVE_POS.LB_CHANGESLOCK;

INSERT INTO PIS_STORITVE_POS.LB_CHANGESLOCK (ID, LOCKED) VALUES (1, 0);

-- Lock Database
UPDATE PIS_STORITVE_POS.LB_CHANGESLOCK SET LOCKED = 1, LOCKEDBY = 'W012823 (192.168.2.132)', LOCKGRANTED = SYSTIMESTAMP WHERE ID = 1 AND LOCKED = 0;

-- Release Database Lock
UPDATE PIS_STORITVE_POS.LB_CHANGESLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1;

